# Generated by Django 4.2.2 on 2023-07-14 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('timestamp', models.FloatField()),
                ('headline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.TextField(primary_key=True, serialize=False)),
                ('video_url', models.TextField()),
                ('video_count', models.IntegerField(default=0)),
                ('video_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaterList',
            fields=[
                ('later_list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
