# Generated by Django 4.2.2 on 2023-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_thumbnail_url',
        ),
        migrations.AlterField(
            model_name='laterlist',
            name='later_list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
